### ISSUE TITLE
Plots appear broken

### ISSUE THREAD

**Issue by Jaeyoung-Lim** [ethz-asl/data-driven-dynamics#167]
@manumerous When running the default command, the plot seems to look quite broken

![Figure_6](https://user-images.githubusercontent.com/5248102/133907891-dc89d853-834b-4200-8285-8fc74c340e9a.png)

To reproduce:
```
make estimate-model
```

**Comment by manumerous** [comment]
Is this still relevant? I think this can be fixed by increasing the size of the window, no?

**Comment by Jaeyoung-Lim** [comment]
@manumerous Is there no way that we can stop the text from breaking? This seems pretty broken for me :)
