### ISSUE TITLE
Unified formatter for python code

### ISSUE THREAD

**Issue by manumerous** [ethz-asl/data-driven-dynamics#221]
In order to have a unified style and avoid white space changes it would be good to have a unified formater. Should be use [Black](https://github.com/psf/black) or do you have a special preference?

**Comment by Jaeyoung-Lim** [comment]
@manumerous Yes please, I was actually looking for one for python

**Comment by manumerous** [comment]
I did not do a very detailed evaluation, but Black seems to be a good option. It is the most popular formatter at the moment and actively enforces all code to be compliant with pep8 and its own rules. So I would suggest to move forward with that. I guess the rest is preference anyways.

**Comment by sjschlapbach** [comment]
Sounds like a great idea to me! I started out with some different formatters, but black seems to be a nice solution to have a well-integrated approach for all Python files in the repository.
I took the liberty to already format all files with it and integrate the formatting rule into the style checking with PR #222.
